config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users

  resources :jobs, only: [ :index, :update, :edit, :destroy ]

  resources :apiaries do
    resources :families do 
      resource :cards, only: [:new, :create, :show ]
      resources :jobs
      resources :journals
      get 'dublicate', to: :dublicate, on: :member
    end
  end
  resources :users, only: [ :show ]
end

app/models/apiary.rb
class Apiary < ActiveRecord::Base
  has_many :families, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
end

app/controllers/apiaries_controller.rb
class ApiariesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_apiary!, only: [ :edit, :update, :show, :destroy ]


  def index
    @apiaries = current_user.apiaries order: "created_at DESC"
  end

  def new
    @apiary = Apiary.new
  end

  def create
    @apiary = Apiary.new apiary_params
    if @apiary.save
      current_user.apiaries << @apiary
      redirect_to apiary_path(@apiary)
    else
      render action: "new"
    end
  end

  def edit
  end

  def update
    if @apiary.update apiary_params
      redirect_to apiaries_path
    else
      render action: 'edit'
    end
  end

  def show
  end

  def destroy
    if @apiary.destroy
      redirect_to apiaries_path
    end
  end


  private

    def load_apiary!
      @apiary = Apiary.find( params[:id] )
    end

    def apiary_params
      # params.require(:apiary).permit :num, bodies_attributes: [ :frame_count, :size_width, :size_height, :color ], wombs_attributes: [ :year, :breed, :prolificacy ]
      params.require(:apiary).permit :title, :id
    end
end

app/helpers/apiaries_helper.rb
module ApiariesHelper
end

app/views/apiaries/_form.html.slim
= simple_form_for apiary do |f|
    h3
      = apiary.new_record? ? "Новая пасека" : "Редактировать пасеку #{apiary.title}"  
    div.form-inputs
      = f.input :title, as: :string, label: "Название пасеки", input_html: { class: 'input-block-level' }


    div.form-actions
      = f.button :submit, value: "#{apiary.new_record? ? 'Создать пасеку' : 'Обновить пасеку'}", class: 'btn btn-primary'

app/views/apiaries/edit.html.slim
section.formbox
  = render 'form', apiary: @apiary

app/views/apiaries/index.html.slim
h2 Мои пасеки 
hr

ul.list
  - @apiaries.each do |apiary|
    li.apiary
      div.dropdown
        a#drop4.dropdown-toggle data-toggle="dropdown" href="#" role="button" 
          | Изменить
          b.caret
        ul#menu1.dropdown-menu aria-labelledby="drop4" role="menu" 
          li role="edit-family" 
            = link_to 'Редактировать', edit_apiary_path(apiary), role: 'menuitem', tabindex: '-1'
          li role="edit-family" 
            = link_to 'Удалить', apiary, method: :delete, role: 'menuitem', tabindex: '-1'


      = link_to apiary do
        dl
          dt = apiary.title
          dd
            | Количество семей:  
            = apiary.families.count
  li.create
    = link_to 'Добавить пасеку', new_apiary_path

app/views/apiaries/new.html.slim
section.formbox
  = render 'form', apiary: @apiary

app/views/apiaries/show.html.slim
h2 
  = "Ульи в #{@apiary.title}" 
hr
section.families
ul.list
  - @apiary.families.each do |family|
    li.family.content_menu data-type="family" style="background-color: #{family.bodies.first.color}"  data-remove-url="#{apiary_family_path(@apiary, family)}"  data-edit-url="#{edit_apiary_family_path(@apiary, family)}"
      div.dropdown
        a#drop4.dropdown-toggle data-toggle="dropdown" href="#" role="button" 
          | Изменить
          b.caret
        ul#menu1.dropdown-menu aria-labelledby="drop4" role="menu" 

          li role="edit-family" 
            = link_to 'Запланировать работу', new_apiary_family_job_path(@apiary, family), role: 'menuitem', tabindex: '-1'          
          li role="edit-family" 
            = link_to 'Записать в журнал...', new_apiary_family_journal_path(@apiary, family), role: 'menuitem', tabindex: '-1'          
          li role="edit-family" 
            = link_to 'Добавить карточку...', new_apiary_family_cards_path(@apiary, family), role: 'menuitem', tabindex: '-1'          
            
          li.divider role="presentation" 

          li role="edit-family" 
            = link_to 'Смотреть журнал', [@apiary, family], role: 'menuitem', tabindex: '-1'          
          li role="edit-family" 
            = link_to 'Смотреть карточку', apiary_family_cards_path(@apiary, family), role: 'menuitem', tabindex: '-1'          

          li.divider role="presentation" 
          
          li role="edit-family" 
            = link_to 'Редактировать', edit_apiary_family_path(@apiary, family), role: 'menuitem', tabindex: '-1'
          li role="edit-family" 
            = link_to 'Дублировать', dublicate_apiary_family_path(@apiary, family), role: 'menuitem', tabindex: '-1'
          
          li.divider role="presentation" 
          

          li role="edit-family" 

            = link_to 'Удалить', [@apiary, family], method: :delete, role: 'menuitem', tabindex: '-1'

  li.create
    = link_to 'Добавить семью', new_apiary_family_path(@apiary)