config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users

  resources :jobs, only: [ :index, :update, :edit, :destroy ]

  resources :apiaries do
    resources :families do 
      resource :cards, only: [:new, :create, :show ]
      resources :jobs
      resources :journals
      get 'dublicate', to: :dublicate, on: :member
    end
  end
  resources :users, only: [ :show ]
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :family


  validates :date, :description, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_apiary!, except: [ :index, :destroy, :edit, :update ]
  before_action :load_family!, except: [ :index, :destroy, :edit, :update ]
  before_action :laod_job!, except: [ :index, :new, :create ]

  def new
    @job = Job.new
  end


  def create
    @job = @family.jobs.build job_params 
    if @job.save
      redirect_to @apiary
    else
      render action: :new
    end
  end


  def index
    families = Family.joins(:jobs).where( apiary_id: current_user.apiary_ids ).pluck :id
    @jobs = Job.where(family_id: families).order('date ASC')
  end

  def edit
    
  end

  def update
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render action: :edit
    end
  end


  def destroy
    @job.destroy
    redirect_to jobs_path
  end

  private

    def load_apiary!
      @apiary = current_user.apiaries.find params[:apiary_id]
    end

    def load_family!
      @family = @apiary.families.find params[:family_id]
    end

    def laod_job!
      @job = Job.find params[:id]
    end

    def job_params
      params.require(:job).permit :date, :description
    end
end
  

app/helpers/jobs_helper.rb
module JobsHelper
  def job_status(time)
    if time.today?
      return 'warning'
    elsif Date.today > time
      return 'error'
    elsif Date.today < time
      return 'success'
    end
    time.today?
  end

end

app/views/jobs/_form.html.slim
= simple_form_for [ @apiary, @family, job] do |f|
  h3
    = job.new_record? ? "Запланировать работу" : "Редактировать работу"  
  div.form-inputs
    = f.input :date, label: 'Число'

    = f.input :description, input_html: { class: 'input-block-level' }, label: 'Описание'
  div.form-actions
    = f.button :submit, value: "#{job.new_record? ? 'Запланировать' : 'Обновить'}", class: 'btn btn-primary'

app/views/jobs/edit.html.slim
section.formbox
  = render 'form', job: @job

app/views/jobs/index.html.slim
h2 Все запланированые работы
hr

div.container
  div.row
    table.table.table-bordered.table-hover.jobs
      thead
        tr
          th Значение цвета
      tbody
        tr.error
          td Прошедшие
        tr.warning
          td На сегодня
        tr.success
          td На будущее
    hr
    table.table.table-bordered.table-hover.jobs
      thead
        tr
          th #
          th Дата
          th Задача
          th Действие
      tbody
        - @jobs.each_with_index do |value, index|
          tr class="#{job_status(value.date.to_date)}"
            td = index
            td 
              = time_tag value.date 
            td
              p = value.description
            
            td.buttons

              .btn-group
                a.btn.dropdown-toggle data-toggle="dropdown" href="#" 
                  | Изменить
                  span.caret
                ul.dropdown-menu
                  li
                    = link_to 'Редактировать', edit_job_path(value)
                  li
                    = link_to 'Удалить', job_path(value), method: :delete

                  /! dropdown menu links

app/views/jobs/new.html.slim
section.formbox
  = render 'form', job: @job