config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users

  resources :jobs, only: [ :index, :update, :edit, :destroy ]

  resources :apiaries do
    resources :families do 
      resource :cards, only: [:new, :create, :show ]
      resources :jobs
      resources :journals
      get 'dublicate', to: :dublicate, on: :member
    end
  end
  resources :users, only: [ :show ]
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_apiary!
  before_action :get_family!
  before_action :get_post!, except: [ :new, :create ]

  def new
    @post = @family.posts.build
    @post.attachments.build
  end


  def create
    @post = @family.posts.build post_params
    if @post.add_attachment_from_and_save( params[:post][:temporary_attachments] ) 
      redirect_to @apiary 
    else
      render action: :new
    end
  end


  def show
    
  end


  def edit
    
  end


  def update
    
  end


  def destroy
    
  end




  private

    def get_apiary!
      @apiary = current_user.apiaries.find params[:apiary_id]
    end

    def get_family!
      @family = @apiary.families.find params[:family_id]
    end

    def get_post!
      @post = @family.posts.find params[:id]
    end

    def post_params 
      params.require(:post).permit :text, :year, :wax, :brood, :honey, :family_weight, :family_strength, body: [ :frame_count, :size_width, :size_height, :color ], new_body: [ :frame_count, :size_width, :size_height, :color ]  
    end


end

app/helpers/journals_helper.rb
module JournalsHelper

  def information_table_data(post)
    html = ''
    data_attributes = %w(family_strength wax brood honey family_weight)
    data_attributes.each do |attribute|
      attribute = post.try(attribute)
      value = attribute.present? ? attribute : 'Без изменений'
      html << content_tag( 'td', value)
    end    
    html.html_safe
  end

end

app/views/journals/_form.html.slim
= simple_form_for [ @apiary, @family, post ], url: apiary_family_journals_path do |f|
  h3 Добавить запись в журнал
  hr
  = f.input :year, as: :date, label: 'Число', input_field: 'str'
  ul.nav.nav-tabs
    li.active
      = link_to 'Текст', '#text', data: { toggle: "tab" }, class: 'tab-switches'
    li
      = link_to 'Данные', '#information', data: { toggle: "tab" }, class: 'tab-switches'
    li
      = link_to 'Фотографии', '#photos', data: { toggle: "tab" }, class: 'tab-switches'
    li
      = link_to 'Изм. корн. корпус', '#root_family_status', data: { toggle: "tab" }, class: 'tab-switches'
    li
      = link_to 'Добавить корпус', '#family_status', data: { toggle: "tab" }, class: 'tab-switches'


  div.tab-content
    div.tab-pane.fade.in.active#text
      = render 'journals/forms/text', form: f
    div.tab-pane.fade.in#information
      = render 'journals/forms/information', form: f
    div.tab-pane.fade.in#photos
      = render 'journals/forms/attachment.html.slim', form: f
    div.tab-pane.fade.in#root_family_status
      = render 'journals/forms/root_family_status.html.slim', form: f, post: post
    div.tab-pane.fade.in#family_status
      = render 'journals/forms/family_status.html.slim', form: f, post: post
            

  hr
    = f.button :submit, value: 'Создать запись', class: 'btn btn-primary left'


- content_for :javascript
  coffee:
    $('a.tab-switches').click (e) ->
      e.preventDefault()
      $(@).tab 'show'

app/views/journals/new.html.slim
section.formbox.without-border.big
  div.hero-unit
    = render 'form', post: @post
    